In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
file_path = '/content/drive/MyDrive/Datasets/city_day.csv'
airpollution = pd.read_csv(file_path)
airpollution.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Delhi,2015-01-01,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,204.5,Severe
1,Mumbai,2015-01-01,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,2.01,19.41,2.86,60.9,Satisfactory
2,Chennai,2015-01-01,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,19.07,10.19,9.63,486.5,Severe
3,Kolkata,2015-01-01,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,9.31,11.65,9.39,174.4,Very Poor
4,Bangalore,2015-01-01,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,6.04,12.74,9.59,489.7,Good

In [ ]:
airpollution.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18265 entries, 0 to 18264
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        18265 non-null  object
 1   Datetime    18265 non-null  object
 2   PM2.5       18265 non-null  float64
 3   PM10        18265 non-null  float64
 4   NO          18265 non-null  float64
 5   NO2         18265 non-null  float64
 6   NOx         18265 non-null  float64
 7   NH3         18265 non-null  float64
 8   CO          18265 non-null  float64
 9   SO2         18265 non-null  float64
 10  O3          18265 non-null  float64
 11  Benzene     18265 non-null  float64
 12  Toluene     18265 non-null  float64
 13  Xylene      18265 non-null  float64
 14  AQI         18265 non-null  float64
 15  AQI_Bucket  18265 non-null  object
dtypes: float64(13), object(3)
memory usage: 2.2+ MB

In [ ]:
airpollution['Datetime'] = pd.to_datetime(airpollution['Datetime'])
airpollution.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18265 entries, 0 to 18264
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        18265 non-null  object
 1   Datetime    18265 non-null  datetime64[ns]
 2   PM2.5       18265 non-null  float64
 3   PM10        18265 non-null  float64
 4   NO          18265 non-null  float64
 5   NO2         18265 non-null  float64
 6   NOx         18265 non-null  float64
 7   NH3         18265 non-null  float64
 8   CO          18265 non-null  float64
 9   SO2         18265 non-null  float64
 10  O3          18265 non-null  float64
 11  Benzene     18265 non-null  float64
 12  Toluene     18265 non-null  float64
 13  Xylene      18265 non-null  float64
 14  AQI         18265 non-null  float64
 15  AQI_Bucket  18265 non-null  object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 2.2+ MB

In [ ]:
airpollution['Month'] = airpollution['Datetime'].dt.month
airpollution['Year'] = airpollution['Datetime'].dt.year
airpollution['Day0fWeek'] = airpollution['Datetime'].dt.dayofweek

In [ ]:
city_dummies = pd.get_dummies(airpollution['City'], prefix='city', dtype=int)
airpollution = pd.concat([airpollution, city_dummies], axis=1)
# Check if 'City' column exists before dropping
airpollution.drop('City', axis=1, inplace=True)
airpollution.head()

,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,...,AQI,AQI_Bucket,Month,Year,Day0fWeek,city_Bangalore,city_Chennai,city_Delhi,city_Kolkata,city_Mumbai
0,2015-01-01,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,...,204.5,Severe,1,2015,3,0,0,1,0,0
1,2015-01-01,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,...,60.9,Satisfactory,1,2015,3,0,0,0,0,1
2,2015-01-01,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,...,486.5,Severe,1,2015,3,0,1,0,0,0
3,2015-01-01,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,...,174.4,Very Poor,1,2015,3,0,0,0,1,0
4,2015-01-01,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,...,489.7,Good,1,2015,3,1,0,0,0,0

In [ ]:
airpollution.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18265 entries, 0 to 18264
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Datetime        18265 non-null  datetime64[ns]
 1   PM2.5           18265 non-null  float64
 2   PM10            18265 non-null  float64
 3   NO              18265 non-null  float64
 4   NO2             18265 non-null  float64
 5   NOx             18265 non-null  float64
 6   NH3             18265 non-null  float64
 7   CO              18265 non-null  float64
 8   SO2             18265 non-null  float64
 9   O3              18265 non-null  float64
 10  Benzene         18265 non-null  float64
 11  Toluene         18265 non-null  float64
 12  Xylene          18265 non-null  float64
 13  AQI             18265 non-null  float64
 14  AQI_Bucket      18265 non-null  object
 15  Month           18265 non-null  int32
 16  Year            18265 non-null  int32
 17  Day0fWeek       18265 non-null  int32
 18  city_Bangalore  18265 non-null  int64
 19  city_Chennai    18265 non-null  int64
 20  city_Delhi      18265 non-null  int64
 21  city_Kolkata    18265 non-null  int64
 22  city_Mumbai     18265 non-null  int64
dtypes: datetime64[ns](1), float64(13), int32(3), int64(5), object(1)
memory usage: 3.0+ MB

In [ ]:
y= airpollution['AQI']
X= airpollution.drop(['AQI','AQI_Bucket'], axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (14612, 21)
X_test shape: (3653, 21)
y_train shape: (14612,)
y_test shape: (3653,)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
X_train = X_train.drop('Datetime', axis=1)
X_test = X_test.drop('Datetime', axis=1)
model.fit(X_train, y_train)
print("Model training is complete!")

Model training is complete!

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14612 entries, 12498 to 15795
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PM2.5           14612 non-null  float64
 1   PM10            14612 non-null  float64
 2   NO              14612 non-null  float64
 3   NO2             14612 non-null  float64
 4   NOx             14612 non-null  float64
 5   NH3             14612 non-null  float64
 6   CO              14612 non-null  float64
 7   SO2             14612 non-null  float64
 8   O3              14612 non-null  float64
 9   Benzene         14612 non-null  float64
 10  Toluene         14612 non-null  float64
 11  Xylene          14612 non-null  float64
 12  Month           14612 non-null  int32
 13  Year            14612 non-null  int32
 14  Day0fWeek       14612 non-null  int32
 15  city_Bangalore  14612 non-null  int64
 16  city_Chennai    14612 non-null  int64
 17  city_Delhi      14612 non-null  int64
 18  city_Kolkata    14612 non-null  int64
 19  city_Mumbai     14612 non-null  int64
dtypes: float64(12), int32(3), int64(5)
memory usage: 2.2 MB

In [ ]:
X_train.head()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,Month,Year,Day0fWeek,city_Bangalore,city_Chennai,city_Delhi,city_Kolkata,city_Mumbai
12498,45.1,386.6,145.9,31.9,234.4,37.1,8.67,23.9,41.1,9.50,28.23,0.90,11,2021,3,0,0,0,1,0
10510,120.4,593.5,191.3,106.1,63.0,43.6,3.65,35.1,144.0,18.34,2.17,0.52,10,2020,5,0,0,1,0,0
13972,382.5,17.8,17.3,93.8,4.7,26.9,7.49,24.9,138.3,13.45,22.42,4.38,8,2022,4,0,1,0,0,0
13578,370.2,156.7,187.9,121.1,114.7,2.6,5.82,12.2,131.3,19.12,17.21,4.73,6,2022,2,0,0,0,1,0
6433,397.8,77.4,136.1,12.2,226.0,14.6,0.80,56.3,41.6,16.47,22.87,2.10,7,2018,1,0,0,0,1,0

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

# Make predictions on the test set
# I drop the 'Datetime' column from X_test since the model was not trained on it
predictions = model.predict(X_test)

# Calculate performance metrics
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

# Print the results
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared Score (R2): {r2}")

Mean Absolute Error (MAE): 125.5082556802628
R-squared Score (R2): -0.020222536577709116